# Generated by Django 3.2.6 on 2021-08-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_auto_20210829_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='tempo_devolucao',
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
